import 'package:freezed_annotation/freezed_annotation.dart';

part 'app_error.freezed.dart';

// Dart sealed class -> restricts inheritance so that all subclasses are known at compile time.
// Dart union class -> represents a type that can be one of multiple variants. Here, AppError can be
//   a ServerError, _NoInternet, or _ValidationError. The `when` method can safely act on each variant.
//
// Factories in Dart -> special constructors that can create an instance, but they are not required
//   to return an instance of the same class. Here, AppError.serverError is a named factory constructor
//   that returns an instance of the private _ServerError class generated by freezed, not a direct
//   instance of AppError. This allows union type behavior and sealed class enforcement.

@Freezed(copyWith: false, fromJson: false, toJson: false)
class AppError with _$AppError {
  const factory AppError.serverError({required String error}) = _ServerError;

  const factory AppError.validationError({
    required ValidationError validationError,
  }) = _ValidationError;

  // const factory AppError.noInternet() = _NoInternet;
  // no internet with nointerneterror
  const factory AppError.noInternet({required NoInternetError error}) =
      _NoInternet;
}

class ServerError {
  const ServerError({this.code = 400, required this.message});

  final int code;
  final String message;
}

class NoInternetError extends ServerError {
  const NoInternetError() : super(message: 'No Internet Connection');
}

class ValidationError extends ServerError {
  const ValidationError({required super.message, required this.errors});

  final Map<String, dynamic> errors;
}

extension AppErrorX on AppError {
  String get errorMessage => switch (this) {
    _ServerError(:final error) => error,
    _ValidationError(:final validationError) => validationError.message,
    _NoInternet(:final error) => error.message,
    _ => 'Something went wrong',
  };

  ValidationError? get validationErrorOrNull => switch (this) {
    _ValidationError(:final validationError) => validationError,
    _ => null,
  };
}
